services:
  - type: web
    name: cyber-attack-leads
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeployTrigger: commit
    envVars:
      - key: SERPAPI_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
